### ISSUE TITLE
Force key-rotate to rotate keys even if oxAuth keys are not expired

### ISSUE THREAD

**Issue by moabu** [GluuFederation/docker-key-rotation#8]
We should consider adding an env `GLUU_FORCE_KEY_ROTATION` which forces keys to be rotated even if the keys are not expired. This is useful in cases of testing or if users would like to change keys that were set for longer periods.

**Comment by iromli** [comment]
`GLUU_KEY_ROTATION_FORCE` will be added instead of `GLUU_FORCE_KEY_ROTATION` to match existing env vars

**Comment by iromli** [comment]
Added in https://github.com/GluuFederation/docker-key-rotation/commit/53b79ec282c49f50cb94aac38d2c9b9f5ece3f7e
